name: Test Spring Boot Application

# Triggers the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java (use the Java version compatible with your project)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '15'
          distribution: 'adopt'  # Options: 'zulu', 'adopt', 'temurin', etc.

      # Step 3: Cache Maven dependencies (to speed up the process)
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the project with Maven and run tests
      - name: Build with Maven
        run: mvn clean install

      # Step 5: Run the tests (this will automatically be part of the Maven build process)
      - name: Run tests
        run: mvn test
